## ControllerDiagram — the XR joypad remap view: a picture of both Touch
## controllers with a leader line from every input to its own dropdown.
##
## Replaces the flat list of ten "Left Grip / Right Trigger" rows. The point is
## that a player who does not know which nub is the "grip" can still see which
## one they are rebinding.
##
## Art is baked line art from the meta-quest-touch-plus glTF (MIT,
## immersive-web/webxr-input-profiles) — see Tools/art/bake_controller_art.py, which
## also emits the ANCHORS table below. The textures are white with the stroke in
## the alpha channel, so ART_TINT recolours them to follow the panel theme.
##
## Anchors are normalized to their texture, so the diagram can be laid out at
## any size without re-baking.
class_name ControllerDiagram
extends Control

## Emitted when the player picks a new RetroPad button for `source`.
## `source` is a ControllerBindings key, e.g. "left_grip".
signal binding_changed(source: String, bit: int)

const ART_LEFT := preload("res://Textures/Controllers/quest_touch_plus_left.png")
const ART_RIGHT := preload("res://Textures/Controllers/quest_touch_plus_right.png")

## Kenney Input Prompts 1.5 (CC0) — the outline set, which reads as light-on-dark
## like the controller line art. The thumbstick press has no outline variant.
const GLYPH_DIR := "res://Textures/InputPrompts/"
const GLYPHS: Dictionary = {
	"left_ax_button": "quest_button_x_outline",
	"left_by_button": "quest_button_y_outline",
	"left_trigger": "quest_trigger_left_outline",
	"left_grip": "quest_grip_left_outline",
	"left_primary_click": "quest_stick_l_press",
	"right_ax_button": "quest_button_a_outline",
	"right_by_button": "quest_button_b_outline",
	"right_trigger": "quest_trigger_right_outline",
	"right_grip": "quest_grip_right_outline",
	"right_primary_click": "quest_stick_r_press",
}
const GLYPH_PX := 42.0

## RetroPad target (ControllerBindings JOYPAD_* bit) -> glyph. No single Kenney
## set covers RetroPad, so this mixes two:
##   * Switch for the face buttons, L/R and the D-pad. Its A/B/X/Y sit in the
##     SAME positions as the SNES pad RetroPad models (A right, B bottom, X top,
##     Y left); the Xbox set arranges them differently and would mislabel all four.
##   * PlayStation for L2/R2, L3/R3 and Select/Start, which are literally
##     printed with those names.
## JOYPAD_NONE has no glyph and stays text-only.
const RETROPAD_GLYPHS: Dictionary = {
	ControllerBindings.JOYPAD_B: "switch_button_b_outline",
	ControllerBindings.JOYPAD_Y: "switch_button_y_outline",
	ControllerBindings.JOYPAD_A: "switch_button_a_outline",
	ControllerBindings.JOYPAD_X: "switch_button_x_outline",
	ControllerBindings.JOYPAD_SELECT: "playstation3_button_select_outline",
	ControllerBindings.JOYPAD_START: "playstation3_button_start_outline",
	ControllerBindings.JOYPAD_UP: "switch_dpad_up_outline",
	ControllerBindings.JOYPAD_DOWN: "switch_dpad_down_outline",
	ControllerBindings.JOYPAD_LEFT: "switch_dpad_left_outline",
	ControllerBindings.JOYPAD_RIGHT: "switch_dpad_right_outline",
	ControllerBindings.JOYPAD_L: "switch_button_l_outline",
	ControllerBindings.JOYPAD_R: "switch_button_r_outline",
	ControllerBindings.JOYPAD_L2: "playstation_trigger_l2_outline",
	ControllerBindings.JOYPAD_R2: "playstation_trigger_r2_outline",
	ControllerBindings.JOYPAD_L3: "playstation_button_l3_outline",
	ControllerBindings.JOYPAD_R3: "playstation_button_r3_outline",
}

const ART_TINT := Color(0.74, 0.78, 0.87)
const LEAD_COLOR := Color(1.0, 0.69, 0.29)
const DOT_COLOR := Color(1.0, 0.80, 0.47)
const LEAD_WIDTH := 2.0
const DOT_RADIUS := 5.0

const MAX_W := 1520.0       # wider than this and the leader lines just get long
const COL_W := 210.0        # dropdown column width: input glyph + target glyph
const GRID_COLS := 6        # 17 icon-only targets: 3 short rows, not 5 tall ones
const ROW_H := 56.0         # VRDropdown's collapsed row height
const ROW_GAP := 26.0
const EDGE_PAD := 24.0      # gap between a column and the art
const ART_GAP := 40.0       # gap between the two controllers
const STUB := 22.0          # horizontal landing before the line angles away

## Normalized anchor per input, generated by Tools/art/bake_controller_art.py.
const ANCHORS: Dictionary = {
	"left": {
		"ax_button": Vector2(0.4705, 0.2116),
		"by_button": Vector2(0.5713, 0.2189),
		"trigger": Vector2(0.8382, 0.4222),
		"grip": Vector2(0.3520, 0.5896),
		"primary_click": Vector2(0.7117, 0.0972),
	},
	"right": {
		"ax_button": Vector2(0.5290, 0.2113),
		"by_button": Vector2(0.4278, 0.2190),
		"trigger": Vector2(0.1618, 0.4226),
		"grip": Vector2(0.6475, 0.5900),
		"primary_click": Vector2(0.2888, 0.0963),
	},
}

## Row order per hand, top to bottom. Sorted by anchor Y so the leader lines run
## in parallel instead of crossing.
const ROW_ORDER: Array = ["primary_click", "ax_button", "by_button", "trigger", "grip"]

var _drops: Dictionary = {}         # source key -> VRDropdown
var _art: Dictionary = {}           # hand -> TextureRect
var _anchor_px: Dictionary = {}     # source key -> Vector2 in local coords
var _band := Rect2()                # the centred, width-capped content area


## Build the ten dropdowns. `button_map` is source key -> RetroPad bit,
## `options` is the [display, id] list shared with the rest of the panel.
func setup(button_map: Dictionary, options: Array) -> void:
	for c in get_children():
		c.queue_free()
		remove_child(c)
	_drops.clear()
	_art.clear()

	var glyph_options := _with_glyphs(options)

	for hand: String in ["left", "right"]:
		var rect := TextureRect.new()
		rect.texture = ART_LEFT if hand == "left" else ART_RIGHT
		rect.stretch_mode = TextureRect.STRETCH_SCALE
		# Without this the texture's own size becomes the minimum and the
		# explicit size set in _relayout() is clamped back up to 870x900.
		rect.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
		rect.modulate = ART_TINT
		rect.mouse_filter = Control.MOUSE_FILTER_IGNORE
		add_child(rect)
		_art[hand] = rect

	# Dropdowns are added after the art so they draw over it.
	for hand: String in ["left", "right"]:
		for key: String in ROW_ORDER:
			var source := "%s_%s" % [hand, key]
			var current: int = button_map.get(source, -1)
			# No label text: the glyph names the input and the leader line
			# points at it on the model, so words said it a third time. The
			# tooltip keeps the name for anyone who wants it.
			var drop := VRDropdown.create("", glyph_options, current, GRID_COLS,
				Vector2(96, ROW_H - 4), 18)
			drop.tooltip_text = ControllerBindings.BUTTON_SOURCE_LABELS.get(source, source)
			# Overlay the option list instead of growing this fixed-height
			# control, which otherwise bleeds into the section below.
			drop.float_panel = true
			var glyph := load(GLYPH_DIR + GLYPHS[source] + ConsolePadDiagram.GLYPH_EXT) as Texture2D
			if glyph:
				drop.set_icon(glyph, GLYPH_PX)
			var captured := source
			drop.item_selected.connect(func(id: Variant) -> void:
				binding_changed.emit(captured, id as int))
			add_child(drop)
			_drops[source] = drop

	_relayout()


## Swap each [display, id] option for its RetroPad glyph, so the chosen target
## reads as a button rather than as the string "L2". The text is dropped where a
## glyph replaces it; JOYPAD_NONE has no glyph and keeps its "None" label.
func _with_glyphs(options: Array) -> Array:
	var out: Array = []
	for entry: Array in options:
		var id: Variant = entry[1]
		if id is int and RETROPAD_GLYPHS.has(id):
			var tex := load(GLYPH_DIR + RETROPAD_GLYPHS[id] + ConsolePadDiagram.GLYPH_EXT) as Texture2D
			if tex:
				out.append(["", id, tex])
				continue
		out.append(entry)
	return out


## The VRDropdown driving `source`, so the owning panel can register it for
## reset. Null before setup().
func get_dropdown(source: String) -> VRDropdown:
	return _drops.get(source) as VRDropdown


## Push a new binding into the UI without emitting binding_changed.
func set_binding(source: String, bit: int) -> void:
	var drop := _drops.get(source) as VRDropdown
	if drop:
		drop.select_id(bit)


func _notification(what: int) -> void:
	if what == NOTIFICATION_RESIZED:
		_relayout()


func _relayout() -> void:
	if _art.is_empty():
		return

	var band_w := minf(size.x, MAX_W)
	_band = Rect2(Vector2((size.x - band_w) * 0.5, 0.0), Vector2(band_w, size.y))

	var rows_h := ROW_ORDER.size() * ROW_H + (ROW_ORDER.size() - 1) * ROW_GAP
	var rows_top := maxf((size.y - rows_h) * 0.5, 0.0)

	for hand: String in ["left", "right"]:
		var col_x := _band.position.x if hand == "left" \
			else _band.end.x - COL_W
		for i in ROW_ORDER.size():
			var drop := _drops.get("%s_%s" % [hand, ROW_ORDER[i]]) as VRDropdown
			if drop == null:
				continue
			drop.position = Vector2(col_x, rows_top + i * (ROW_H + ROW_GAP))
			drop.size = Vector2(COL_W, ROW_H)
			# Keep the floating option list inside this control's band so it
			# never covers the section below.
			drop.float_max_bottom = global_position.y + size.y

	# Art: fit the height, then shrink if the pair would reach the columns.
	var avail_w := _band.size.x - 2.0 * (COL_W + EDGE_PAD) - ART_GAP
	var art_h := size.y - 20.0
	var aspect := float(ART_LEFT.get_width()) / float(ART_LEFT.get_height())
	var art_w := art_h * aspect
	if art_w * 2.0 > avail_w:
		art_w = avail_w * 0.5
		art_h = art_w / aspect

	var mid := _band.position.x + _band.size.x * 0.5
	var art_top := (size.y - art_h) * 0.5
	var rects := {
		"left": Rect2(Vector2(mid - ART_GAP * 0.5 - art_w, art_top), Vector2(art_w, art_h)),
		"right": Rect2(Vector2(mid + ART_GAP * 0.5, art_top), Vector2(art_w, art_h)),
	}

	_anchor_px.clear()
	for hand: String in ["left", "right"]:
		var r: Rect2 = rects[hand]
		var art_rect := _art[hand] as TextureRect
		art_rect.position = r.position
		art_rect.size = r.size
		var table: Dictionary = ANCHORS[hand]
		for key: String in table:
			var uv: Vector2 = table[key]
			_anchor_px["%s_%s" % [hand, key]] = r.position + uv * r.size

	queue_redraw()


func _draw() -> void:
	for hand: String in ["left", "right"]:
		var left_side := hand == "left"
		for i in ROW_ORDER.size():
			var source := "%s_%s" % [hand, ROW_ORDER[i]]
			var drop := _drops.get(source) as VRDropdown
			if drop == null or not _anchor_px.has(source):
				continue

			var anchor: Vector2 = _anchor_px[source]
			# Meet the row, not the expanded panel: the toggle is the top row.
			var edge := Vector2(
				drop.position.x + (COL_W if left_side else 0.0),
				drop.position.y + ROW_H * 0.5)

			# A short horizontal landing, then straight to the dot. An
			# orthogonal elbow route collides here: ax_button and by_button sit
			# ~3 px apart in Y, so their long horizontal runs drew on top of one
			# another. Rows are ordered by anchor Y (see ROW_ORDER), which keeps
			# the straight runs fanned out and non-crossing.
			var stub := Vector2(edge.x + (STUB if left_side else -STUB), edge.y)
			draw_line(edge, stub, LEAD_COLOR, LEAD_WIDTH, true)
			draw_line(stub, anchor, LEAD_COLOR, LEAD_WIDTH, true)
			draw_circle(anchor, DOT_RADIUS, DOT_COLOR, true)
