## GamepadDiagram — the physical-pad remap view: a picture of a gamepad with a
## leader line from every input to its own dropdown.
##
## The sibling of ControllerDiagram, for real joypads rather than XR controllers.
## Same reasoning: a player who does not know which shoulder is "LB" can still see
## which one they are rebinding.
##
## Art is drawn, not baked — see Tools/art/gen_gamepad_art.py, which also emits the
## ANCHORS table below. It is an Xbox *layout* (offset sticks, ABXY diamond,
## bumpers and triggers) and deliberately not an Xbox: no logo, nothing traced, so
## there is no mark being borrowed. The SVG is white with the drawing in its
## alpha, so ART_TINT recolours it to follow the panel theme.
##
## Direction is the inverse of the data it edits. GamepadBindings stores
## RetroPad target -> physical binding ("b" -> "btn:0"); anchored on a picture of
## the pad, the useful question is the other one — this physical button, what does
## it do? So the rows read input -> target, and the map is inverted on the way in
## and back out on the way out.
class_name GamepadDiagram
extends Control

## Emitted when the player picks a new RetroPad target for a physical input.
## `input` is a key of ANCHORS; `target` is a GamepadBindings target, or "" for
## unbound.
signal binding_changed(input: String, target: String)

const ART := preload("res://Textures/Controllers/gamepad_line.svg")

const GLYPH_DIR := "res://Textures/InputPrompts/"

## Physical input -> the Kenney glyph naming it, and the GamepadBindings encoding
## it corresponds to. Indices follow GamepadBindings.JOY_BUTTON_NAMES, which is
## the SDL layout every pad Godot reports is normalised onto.
const INPUTS: Dictionary = {
	"lt":          {"glyph": "xbox_lt_outline",         "bind": "axis:4:+"},
	"lb":          {"glyph": "xbox_lb_outline",         "bind": "btn:9"},
	"ls":          {"glyph": "xbox_stick_l_press",      "bind": "btn:7"},
	"back":        {"glyph": "xbox_button_view_outline", "bind": "btn:4"},
	"dpad_up":     {"glyph": "xbox_dpad_up_outline",    "bind": "btn:11"},
	"dpad_left":   {"glyph": "xbox_dpad_left_outline",  "bind": "btn:13"},
	"dpad_right":  {"glyph": "xbox_dpad_right_outline", "bind": "btn:14"},
	"dpad_down":   {"glyph": "xbox_dpad_down_outline",  "bind": "btn:12"},
	"rt":          {"glyph": "xbox_rt_outline",         "bind": "axis:5:+"},
	"rb":          {"glyph": "xbox_rb_outline",         "bind": "btn:10"},
	"y":           {"glyph": "xbox_button_y_outline",   "bind": "btn:3"},
	"x":           {"glyph": "xbox_button_x_outline",   "bind": "btn:2"},
	"start":       {"glyph": "xbox_button_menu_outline", "bind": "btn:6"},
	"b":           {"glyph": "xbox_button_b_outline",   "bind": "btn:1"},
	"a":           {"glyph": "xbox_button_a_outline",   "bind": "btn:0"},
	"rs":          {"glyph": "xbox_stick_r_press",      "bind": "btn:8"},
}

## Tooltip names, since the rows carry glyphs rather than words.
const INPUT_LABELS: Dictionary = {
	"lt": "Left Trigger", "lb": "Left Bumper", "ls": "Left Stick (click)",
	"back": "View / Back", "dpad_up": "D-pad Up", "dpad_left": "D-pad Left",
	"dpad_right": "D-pad Right", "dpad_down": "D-pad Down",
	"rt": "Right Trigger", "rb": "Right Bumper", "y": "Y (top)", "x": "X (left)",
	"start": "Menu / Start", "b": "B (right)", "a": "A (bottom)",
	"rs": "Right Stick (click)",
}

## RetroPad target -> glyph, matching ControllerDiagram's choice: Switch for the
## face buttons, L/R and the D-pad, because its A/B/X/Y sit where the SNES-style
## RetroPad models put them; PlayStation for the ones literally printed L2/R2/
## L3/R3/Select/Start.
const TARGET_GLYPHS: Dictionary = {
	"b": "switch_button_b_outline", "y": "switch_button_y_outline",
	"a": "switch_button_a_outline", "x": "switch_button_x_outline",
	"select": "playstation3_button_select_outline",
	"start": "playstation3_button_start_outline",
	"up": "switch_dpad_up_outline", "down": "switch_dpad_down_outline",
	"left": "switch_dpad_left_outline", "right": "switch_dpad_right_outline",
	"l": "switch_button_l_outline", "r": "switch_button_r_outline",
	"l2": "playstation_trigger_l2_outline", "r2": "playstation_trigger_r2_outline",
	"l3": "playstation_button_l3_outline", "r3": "playstation_button_r3_outline",
}

const GLYPH_PX := 42.0
const ART_TINT := Color(0.74, 0.78, 0.87)
const LEAD_COLOR := Color(1.0, 0.69, 0.29)
const DOT_COLOR := Color(1.0, 0.80, 0.47)
const LEAD_WIDTH := 2.0
const DOT_RADIUS := 5.0

const MAX_W := 1520.0
const COL_W := 210.0
const GRID_COLS := 6
const ROW_H := 50.0
const ROW_GAP := 16.0
const EDGE_PAD := 24.0
const STUB := 22.0

## Normalized anchors, generated by Tools/art/gen_gamepad_art.py.
const ANCHORS: Dictionary = {
	"lt": Vector2(0.3000, 0.1139),
	"rt": Vector2(0.7000, 0.1139),
	"lb": Vector2(0.3000, 0.1778),
	"rb": Vector2(0.7000, 0.1778),
	"ls": Vector2(0.2680, 0.3639),
	"rs": Vector2(0.6050, 0.5667),
	"dpad_up": Vector2(0.3980, 0.5028),
	"dpad_down": Vector2(0.3980, 0.6306),
	"dpad_left": Vector2(0.3520, 0.5667),
	"dpad_right": Vector2(0.4440, 0.5667),
	"y": Vector2(0.7220, 0.2944),
	"b": Vector2(0.7780, 0.3722),
	"a": Vector2(0.7220, 0.4500),
	"x": Vector2(0.6660, 0.3722),
	"guide": Vector2(0.5000, 0.2889),
	"back": Vector2(0.4410, 0.3722),
	"start": Vector2(0.5590, 0.3722),
}

## Column contents. Every input sits in the column on its own side of the pad, so
## no line has to cross the picture; the order within a column is what decides
## whether the leader lines cross each other.
##
## Sorting by anchor Y is only an approximation, and here it is wrong. Start sits
## higher than A (y .372 vs .450) so Y-order puts it first, but it is also much
## further left (x .559 vs .722), so its longer, shallower line cuts across A's. A
## has to come first. The face buttons and the d-pad each crowd several anchors
## onto one row, which is why this pad has the problem and the Touch controllers
## did not.
##
## Both orders were chosen by counting segment intersections rather than by eye,
## and swept over panel sizes 900-1700 x 500-800: zero crossings at all 272, where
## Start-before-A crossed at 259 of them. Re-run that count if an anchor moves.
##
## `guide` is deliberately absent: it has an anchor so the art stays reusable, but
## Windows and Steam both intercept it, so it is a poor binding target. The
## press-to-bind list can still reach it.
const LEFT_ORDER: Array = ["lt", "lb", "ls", "back", "dpad_up", "dpad_left",
	"dpad_right", "dpad_down"]
const RIGHT_ORDER: Array = ["rt", "rb", "y", "b", "x", "a", "start", "rs"]

var _drops: Dictionary = {}
var _art: TextureRect = null
var _anchor_px: Dictionary = {}
var _band := Rect2()


## `button_map` is GamepadBindings' target -> binding dictionary.
func setup(button_map: Dictionary) -> void:
	for c in get_children():
		c.queue_free()
		remove_child(c)
	_drops.clear()

	var by_input := invert(button_map)
	var options := _target_options()

	_art = TextureRect.new()
	_art.texture = ART
	_art.stretch_mode = TextureRect.STRETCH_SCALE
	# Without this the texture's own size becomes the minimum and the explicit
	# size set in _relayout() is clamped back up.
	_art.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	_art.modulate = ART_TINT
	_art.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(_art)

	# Dropdowns after the art so they draw over it.
	for input: String in LEFT_ORDER + RIGHT_ORDER:
		var current: String = by_input.get(input, "")
		var drop := VRDropdown.create("", options, current, GRID_COLS,
			Vector2(96, ROW_H - 4), 18)
		drop.tooltip_text = INPUT_LABELS.get(input, input)
		drop.float_panel = true
		var glyph := load(GLYPH_DIR + String(INPUTS[input]["glyph"])
			+ ConsolePadDiagram.GLYPH_EXT) as Texture2D
		if glyph:
			drop.set_icon(glyph, GLYPH_PX)
		var captured := input
		drop.item_selected.connect(func(id: Variant) -> void:
			binding_changed.emit(captured, String(id)))
		add_child(drop)
		_drops[input] = drop

	_relayout()


## GamepadBindings' target -> binding, read the way the picture asks it:
## physical input -> the target it drives. A target bound to something this
## diagram does not draw is dropped; a target bound to nothing contributes
## nothing, which is what leaves that input showing "None".
static func invert(button_map: Dictionary) -> Dictionary:
	var bind_to_input: Dictionary = {}
	for input: String in INPUTS:
		bind_to_input[String(INPUTS[input]["bind"])] = input
	var out: Dictionary = {}
	for target: String in button_map:
		var input: Variant = bind_to_input.get(String(button_map[target]))
		if input != null:
			out[input] = target
	return out


## The reverse, for saving. Targets whose input is unset are explicitly "none"
## rather than absent, so clearing a binding actually clears it.
static func to_button_map(by_input: Dictionary) -> Dictionary:
	var out: Dictionary = {}
	for target: String in GamepadBindings.TARGET_ORDER:
		out[target] = "none"
	for input: String in by_input:
		var target := String(by_input[input])
		if target != "" and out.has(target):
			out[target] = String(INPUTS[input]["bind"])
	return out


func _target_options() -> Array:
	var out: Array = [["None", ""]]
	for target: String in GamepadBindings.TARGET_ORDER:
		var label := String(GamepadBindings.TARGET_LABELS.get(target, target))
		if TARGET_GLYPHS.has(target):
			var tex := load(GLYPH_DIR + String(TARGET_GLYPHS[target])
				+ ConsolePadDiagram.GLYPH_EXT) as Texture2D
			if tex:
				out.append(["", target, tex])
				continue
		out.append([label, target])
	return out


## The VRDropdown driving `input`, so the owning panel can register it for reset.
func get_dropdown(input: String) -> VRDropdown:
	return _drops.get(input) as VRDropdown


## Push a binding into the UI without emitting binding_changed.
func set_binding(input: String, target: String) -> void:
	var drop := _drops.get(input) as VRDropdown
	if drop:
		drop.select_id(target)


func _notification(what: int) -> void:
	if what == NOTIFICATION_RESIZED:
		_relayout()


func _relayout() -> void:
	if _art == null or not is_instance_valid(_art):
		return

	var band_w := minf(size.x, MAX_W)
	_band = Rect2(Vector2((size.x - band_w) * 0.5, 0.0), Vector2(band_w, size.y))

	var rows := maxi(LEFT_ORDER.size(), RIGHT_ORDER.size())
	var rows_h := rows * ROW_H + (rows - 1) * ROW_GAP
	var rows_top := maxf((size.y - rows_h) * 0.5, 0.0)

	for side in 2:
		var order: Array = LEFT_ORDER if side == 0 else RIGHT_ORDER
		var col_x := _band.position.x if side == 0 else _band.end.x - COL_W
		for i in order.size():
			var drop := _drops.get(order[i]) as VRDropdown
			if drop == null:
				continue
			drop.position = Vector2(col_x, rows_top + i * (ROW_H + ROW_GAP))
			drop.size = Vector2(COL_W, ROW_H)
			# Keep the floating option list inside this control's band.
			drop.float_max_bottom = global_position.y + size.y

	var avail_w := _band.size.x - 2.0 * (COL_W + EDGE_PAD)
	var art_h := size.y - 20.0
	var aspect := float(ART.get_width()) / float(ART.get_height())
	var art_w := art_h * aspect
	if art_w > avail_w:
		art_w = avail_w
		art_h = art_w / aspect

	var r := Rect2(
		Vector2(_band.position.x + (_band.size.x - art_w) * 0.5, (size.y - art_h) * 0.5),
		Vector2(art_w, art_h))
	_art.position = r.position
	_art.size = r.size

	_anchor_px.clear()
	for key: String in ANCHORS:
		var uv: Vector2 = ANCHORS[key]
		_anchor_px[key] = r.position + uv * r.size

	queue_redraw()


func _draw() -> void:
	for side in 2:
		var order: Array = LEFT_ORDER if side == 0 else RIGHT_ORDER
		var left_side := side == 0
		for i in order.size():
			var input: String = order[i]
			var drop := _drops.get(input) as VRDropdown
			if drop == null or not _anchor_px.has(input):
				continue

			var anchor: Vector2 = _anchor_px[input]
			# Meet the row, not the expanded panel: the toggle is the top row.
			var edge := Vector2(
				drop.position.x + (COL_W if left_side else 0.0),
				drop.position.y + ROW_H * 0.5)
			var stub := Vector2(edge.x + (STUB if left_side else -STUB), edge.y)
			draw_line(edge, stub, LEAD_COLOR, LEAD_WIDTH, true)
			draw_line(stub, anchor, LEAD_COLOR, LEAD_WIDTH, true)
			draw_circle(anchor, DOT_RADIUS, DOT_COLOR, true)
